"use client";

import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { AuthContextProvider } from "./context/AuthContext";
import { TimersContextProvider } from "./context/TimerContext";

//theme
import "../public/theme.css";
import "primeicons/primeicons.css";
import "primereact/resources/primereact.min.css";
import "primeflex/primeflex.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vehicle Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <TimersContextProvider>
            <Navbar />
            {children}
          </TimersContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
